# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
        #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        # If you're using guard-based authentication, you have to use this one:
         - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
    google:
        enabled: true
#        server_name: 'Testauth'       # Server name used in QR code
#        issuer: 'My Issuer'            # Issuer name used in QR code
#        digits: 6                      # Number of digits in authentication code
#        window: 1                      # How many codes before/after the current one would be accepted as valid
##        template: security/2fa_form.html.twig   # Template used to render the authentication form